meta:
  id: enum__item_limit_type
  endian: le
  license: GPLv2
  imports:
    - ../aux_types
seq:
  - id: data
    type: aux_types::vlq_base128_le_s
instances:
  value:
    value: data.value
    enum: item_limit_type
enums:
  item_limit_type:
    0: item_limit_none
    1: item_limit_unlimited
    2: item_limit_gm
    3: item_limit_quest
    4: item_limit_city_upgrade
    5: item_limit_unlock_trans_point
    6: item_limit_unlock_dungeon
    7: item_limit_investigation
    8: item_limit_player_level_upgrade
    9: item_limit_push_tips_reward
    10: item_limit_avatar_fetter_reward
    11: item_limit_world_area_explore_event_reward
    12: item_limit_activity_sea_lamp
    13: item_limit_battle_pass_paid_reward
    14: item_limit_oneoff_big_world_drop
    15: item_limit_gameplay_niche
    16: item_limit_oneoff_dungeon_drop
    17: item_limit_oneoff_plunder_drop
    18: item_limit_oneoff_subfield_drop
    19: item_limit_big_world_chest
    20: item_limit_gacha_token_drop
    22: item_limit_daily_big_world_drop
    23: item_limit_daily_dungeon_drop
    24: item_limit_daily_plunder_drop
    25: item_limit_daily_subfield_drop
    26: item_limit_daily_sea_lamp_drop
    27: item_limit_normal_dungeon
    28: item_limit_daily_task
    29: item_limit_daily_task_score
    30: item_limit_rand_task_drop
    31: item_limit_expedition
    32: item_limit_small_monster_die
    33: item_limit_elite_monster_die
    34: item_limit_boss_monster_die
    35: item_limit_big_boss_monster_die
    36: item_limit_small_env_animal_die
    37: item_limit_monster_excel_drop
    38: item_limit_repeatable_quest_reward
    39: item_limit_env_animal
    40: item_limit_gather
    41: item_limit_operation_daily_activity
    42: item_limit_quest_add_item
    43: item_limit_bonus_activity
    44: item_limit_tower_monthly
    45: item_limit_battle_pass_level_reward
    46: item_limit_sign_in
    47: item_limit_gacha
    48: item_limit_shop
    49: item_limit_cook
    50: item_limit_compound
    51: item_limit_combine
    52: item_limit_forge
    53: item_limit_random_chest
    54: item_limit_use_item
    55: item_limit_use_item_reward
    56: item_limit_blossom_chest_drop
    57: item_limit_mp_play_drop
    58: item_limit_forge_drop
    59: item_limit_mp_play_crucible_drop
    60: item_limit_activity_crucible_reward
    61: item_limit_activity_reward
    62: item_limit_activity_trial_avatar
    63: item_limit_activity_salesman
    64: item_limit_rebate
    65: item_limit_month_card
    67: item_limit_birthday_benefit
    68: item_limit_achievement_reward
    69: item_limit_achievement_goal_reward
    70: item_limit_destroy_return_material
    71: item_limit_tower_reward
    72: item_limit_share_reward
    73: item_limit_fetter_level_reward
    74: item_limit_dungeon_first_pass_reward
    75: item_limit_codex_levelup_reward
    76: item_limit_activity_delivery
    77: item_limit_city_reputation_level
    78: item_limit_city_reputation_quest
    79: item_limit_upgrade_weapon_return_material
    80: item_limit_city_reputation_request
    81: item_limit_hunting_reward
    82: item_limit_city_reputation_explore
    83: item_limit_activity_flight_reward
    84: item_limit_activity_aster_reward
    85: item_limit_activity_aster_drop
    86: item_limit_activity_drgaon_spine_reward
    87: item_limit_activity_dragon_spine_drop
    88: item_limit_snow_mountain_tree_task
    89: item_limit_snow_mountain_tree_level
    90: item_limit_activity_salesman_chest_drop
    91: item_limit_activity_effigy_reward
    92: item_limit_reunion_reward
    93: item_limit_avatar_promote_reward
    94: item_limit_activity_salesman_mp
    95: item_limit_activity_treasure_map_reward
    96: item_limit_resin_card
    97: item_limit_activity_blessing
    98: item_limit_miracle_ring_reward
    99: item_limit_activity_expedition_reward
    100: item_limit_mechanicus_battle_settle_reward
    101: item_limit_sea_lamp_activity_avatar_reward
    1401: item_limit_player_exp_overflow_transform
    1402: item_limit_activity_arena_challenge_reward
    1403: item_limit_coop_task_reward
    1404: item_limit_water_spirit_reward
    1405: item_limit_region_search_reward
    1406: item_limit_water_spirit_drop
    1407: item_limtt_activity_fleur_fair_reward
    1501: item_limit_hit_tree_drop
    1502: item_limit_activity_mist_trial
    1503: item_limit_activity_channeller_slab
    1504: item_limit_activity_hide_and_seek
    1505: item_limit_activity_find_hilichurl
    1506: item_limit_furniture_make_cancel
    1507: item_limit_home_levelup_reward
    1508: item_limit_furniture_make
    1509: item_limit_activity_condition_mail_reward
    1510: item_limit_battle_pass_notify_mail_reward
    1511: item_limit_activity_channeller_slab_avatar_reward
    1512: item_limit_home_resource
    1513: item_limit_operation_welfare
    1601: item_limit_activity_summer_time_reward
    1602: item_limit_activity_echo_shell
    1603: item_limit_reliquary_decompose
    1604: item_limit_home_fetter
    1605: item_limit_home_event_reward
    1606: item_limit_activity_buoyant_combat_reward
    1607: item_limit_activity_bounce_conjuring_reward
    2000: item_limit_oraionokami_reward
    2001: item_limit_book_leaf_drop
    2002: item_limit_exploration_line_level_reward
    2003: item_limit_activity_blitz_rush_reward
    2004: item_limit_activity_blitz_rush_avatar_reward
    2005: item_limit_activity_chess_reward
    2006: item_limit_home_plant_box_seed_drop
    2007: item_limit_home_plant_gather_drop
    2008: item_limit_home_furniture_make_return
    2100: item_limit_activity_sumo
    2101: item_limit_activity_luna_rite
    2102: item_limit_fish_reward
    2103: item_limit_activity_moonfin_trial
    2104: item_limit_activity_luna_rite_drop
    2200: item_limit_activity_roguelike_dungeon
    2201: item_limit_activity_roguelike_dungeon_avatar_reward
    2202: item_limit_activity_plant_flower
    2203: item_limit_activity_dig_reward
    2204: item_limit_activity_dig_drop
    2205: item_limit_activity_music_game_reward
