meta:
  id: disp__config_ability_action
  endian: le
  license: AGPL-3.0-or-later
  imports:
    - ../../../../aux_types
    - disp__config_ability_action
    - ../config_ability_action
    - ../ConfigAbilityAction/base_utility_action
    - ../ConfigAbilityAction/apply_modifier
    - ../ConfigAbilityAction/apply_level_modifier
    - ../ConfigAbilityAction/attach_modifier
    - ../ConfigAbilityAction/remove_unique_modifier
    - ../ConfigAbilityAction/fire_effect
    - ../ConfigAbilityAction/fire_sub_emitter_effect
    - ../ConfigAbilityAction/fire_effect_for_storm
    - ../ConfigAbilityAction/fire_effect_to_target
    - ../ConfigAbilityAction/fire_hit_effect
    - ../ConfigAbilityAction/avatar_skill_start
    - ../ConfigAbilityAction/entity_do_skill
    - ../ConfigAbilityAction/avatar_enter_focus
    - ../ConfigAbilityAction/avatar_exit_focus
    - ../ConfigAbilityAction/avatar_enter_view_bias
    - ../ConfigAbilityAction/avatar_exit_view_bias
    - ../ConfigAbilityAction/avatar_exit_climb
    - ../ConfigAbilityAction/avatar_camera_param
    - ../ConfigAbilityAction/avatar_enter_camera_shot
    - ../ConfigAbilityAction/avatar_exit_camera_shot
    - ../ConfigAbilityAction/play_emo_sync
    - ../ConfigAbilityAction/control_emotion
    - ../ConfigAbilityAction/spawn_attach
    - ../ConfigAbilityAction/turn_direction
    - ../ConfigAbilityAction/turn_direction_to_pos
    - ../ConfigAbilityAction/set_camera_lock_time
    - ../ConfigAbilityAction/fire_monster_being_hit_after_image
    - ../ConfigAbilityAction/fire_avatar_being_hit_after_image
    - ../ConfigAbilityAction/attach_effect
    - ../ConfigAbilityAction/attach_light
    - ../ConfigAbilityAction/add_global_value
    - ../ConfigAbilityAction/set_global_value
    - ../ConfigAbilityAction/multiply_global_value
    - ../ConfigAbilityAction/copy_global_value
    - ../ConfigAbilityAction/set_global_value_list
    - ../ConfigAbilityAction/set_global_value_to_override_map
    - ../ConfigAbilityAction/set_random_override_map_value
    - ../ConfigAbilityAction/set_override_map_value
    - ../ConfigAbilityAction/set_crystal_shield_hp_to_override_map
    - ../ConfigAbilityAction/set_system_value_to_override_map
    - ../ConfigAbilityAction/set_global_value_by_target_distance
    - ../ConfigAbilityAction/clear_global_value
    - ../ConfigAbilityAction/sum_target_weight_to_self_global_value
    - ../ConfigAbilityAction/set_global_pos
    - ../ConfigAbilityAction/add_global_pos
    - ../ConfigAbilityAction/clear_global_pos
    - ../ConfigAbilityAction/set_global_dir
    - ../ConfigAbilityAction/push_pos
    - ../ConfigAbilityAction/clear_pos
    - ../ConfigAbilityAction/get_pos
    - ../ConfigAbilityAction/damage_by_attack_value
    - ../ConfigAbilityAction/heal_sp
    - ../ConfigAbilityAction/heal_hp
    - ../ConfigAbilityAction/lose_hp
    - ../ConfigAbilityAction/enable_rocket_jump
    - ../ConfigAbilityAction/force_trigger_jump
    - ../ConfigAbilityAction/enable_after_image
    - ../ConfigAbilityAction/act_time_slow
    - ../ConfigAbilityAction/trigger_ability
    - ../ConfigAbilityAction/remove_modifier
    - ../ConfigAbilityAction/set_ai_param
    - ../ConfigAbilityAction/act_camera_shake
    - ../ConfigAbilityAction/act_camera_radial_blur
    - ../ConfigAbilityAction/set_animator_bool
    - ../ConfigAbilityAction/set_animator_int
    - ../ConfigAbilityAction/set_animator_float
    - ../ConfigAbilityAction/set_animator_trigger
    - ../ConfigAbilityAction/reset_animator_trigger
    - ../ConfigAbilityAction/set_material_param_float_by_transform
    - ../ConfigAbilityAction/debug_log
    - ../ConfigAbilityAction/trigger_bullet
    - ../ConfigAbilityAction/trigger_attack_event
    - ../ConfigAbilityAction/trigger_attack_target_map_event
    - ../ConfigAbilityAction/enable_wet_electric_hit_box
    - ../ConfigAbilityAction/create_entity
    - ../ConfigAbilityAction/try_trigger_platform_start_move
    - ../ConfigAbilityAction/kill_gadget
    - ../ConfigAbilityAction/kill_self
    - ../ConfigAbilityAction/trigger_audio
    - ../ConfigAbilityAction/trigger_drop_equip_parts
    - ../ConfigAbilityAction/trigger_throw_equip_part
    - ../ConfigAbilityAction/trigger_create_gadget_to_equip_part
    - ../ConfigAbilityAction/trigger_aux_weapon_trans
    - ../ConfigAbilityAction/trigger_gadget_interactive
    - ../ConfigAbilityAction/trigger_set_visible
    - ../ConfigAbilityAction/trigger_set_cast_shadow
    - ../ConfigAbilityAction/trigger_set_pass_through
    - ../ConfigAbilityAction/trigger_set_renderers_enable
    - ../ConfigAbilityAction/trigger_hide_weapon
    - ../ConfigAbilityAction/trigger_taunt
    - ../ConfigAbilityAction/trigger_set_chest_lock
    - ../ConfigAbilityAction/clear_lock_target
    - ../ConfigAbilityAction/set_pose_bool
    - ../ConfigAbilityAction/set_pose_int
    - ../ConfigAbilityAction/set_pose_float
    - ../ConfigAbilityAction/trigger_face_animation
    - ../ConfigAbilityAction/enable_crash_damage
    - ../ConfigAbilityAction/set_crash_damage
    - ../ConfigAbilityAction/try_find_blink_point
    - ../ConfigAbilityAction/try_find_blink_point_by_born
    - ../ConfigAbilityAction/do_blink
    - ../ConfigAbilityAction/avatar_do_blink
    - ../ConfigAbilityAction/enable_hit_box_by_name
    - ../ConfigAbilityAction/enable_push_collider_name
    - ../ConfigAbilityAction/enable_scene_transform_by_name
    - ../ConfigAbilityAction/generate_elem_ball
    - ../ConfigAbilityAction/randomed
    - ../ConfigAbilityAction/hide_ui_bill_board
    - ../ConfigAbilityAction/send_effect_trigger
    - ../ConfigAbilityAction/change_follow_damp_time
    - ../ConfigAbilityAction/set_self_attack_target
    - ../ConfigAbilityAction/force_init_massive_entity
    - ../ConfigAbilityAction/enable_head_control
    - ../ConfigAbilityAction/enable_part_control
    - ../ConfigAbilityAction/start_dither
    - ../ConfigAbilityAction/summon
    - ../ConfigAbilityAction/attach_ability_state_resistance
    - ../ConfigAbilityAction/fire_ai_sound_event
    - ../ConfigAbilityAction/add_element_durability
    - ../ConfigAbilityAction/set_part_control_target
    - ../ConfigAbilityAction/drop_subfield
    - ../ConfigAbilityAction/enable_gadget_intee
    - ../ConfigAbilityAction/remove_velocity_force
    - ../ConfigAbilityAction/execute_group_trigger
    - ../ConfigAbilityAction/re_trigger_ai_skill_initial_cd
    - ../ConfigAbilityAction/set_ai_skill_cd_available_now
    - ../ConfigAbilityAction/set_ai_skill_gcd
    - ../ConfigAbilityAction/enable_ai_stealthy
    - ../ConfigAbilityAction/unlock_skill
    - ../ConfigAbilityAction/add_avatar_skill_info
    - ../ConfigAbilityAction/remove_avatar_skill_info
    - ../ConfigAbilityAction/set_can_die_immediately
    - ../ConfigAbilityAction/play_emoji_bubble
    - ../ConfigAbilityAction/attach_bullet_aim_point
    - ../ConfigAbilityAction/enable_bullet_collision_plugin_trigger
    - ../ConfigAbilityAction/guide_paimon_disappear_end
    - ../ConfigAbilityAction/set_paimon_look_at_camera
    - ../ConfigAbilityAction/paimon_action
    - ../ConfigAbilityAction/set_paimon_look_at_avatar
    - ../ConfigAbilityAction/set_paimon_temp_offset
    - ../ConfigAbilityAction/set_keep_in_air_velocity_force
    - ../ConfigAbilityAction/force_air_state_fly
    - ../ConfigAbilityAction/to_nearst_anchor_point
    - ../ConfigAbilityAction/push_dvalin_s01process
    - ../ConfigAbilityAction/set_dvalin_s01fly_state
    - ../ConfigAbilityAction/regist_to_stage_script
    - ../ConfigAbilityAction/sync_to_stage_script
    - ../ConfigAbilityAction/calc_dvalin_s04reborn_point
    - ../ConfigAbilityAction/trigger_player_die
    - ../ConfigAbilityAction/reset_enviro_eular
    - ../ConfigAbilityAction/set_emission_scaler
    - ../ConfigAbilityAction/enter_camera_lock
    - ../ConfigAbilityAction/show_ui_combat_bar
    - ../ConfigAbilityAction/show_screen_effect
    - ../ConfigAbilityAction/add_server_buff
    - ../ConfigAbilityAction/remove_server_buff
    - ../ConfigAbilityAction/modify_avatar_skill_cd
    - ../ConfigAbilityAction/modify_vehicle_skill_cd
    - ../ConfigAbilityAction/reset_ability_special
    - ../ConfigAbilityAction/enable_avatar_fly_state_trail
    - ../ConfigAbilityAction/show_reminder
    - ../ConfigAbilityAction/update_reaction_damage
    - ../ConfigAbilityAction/execute_gadget_lua
    - ../ConfigAbilityAction/set_weapon_bind_state
    - ../ConfigAbilityAction/set_weapon_attach_point_real_name
    - ../ConfigAbilityAction/set_avatar_can_shake_off
    - ../ConfigAbilityAction/enable_main_interface
    - ../ConfigAbilityAction/change_play_mode
    - ../ConfigAbilityAction/enable_camera_dof
    - ../ConfigAbilityAction/enable_hit_auto_redirect
    - ../ConfigAbilityAction/clear_endura
    - ../ConfigAbilityAction/rush_move
    - ../ConfigAbilityAction/reset_ai_attack_target
    - ../ConfigAbilityAction/reset_ai_resist_taunt_level
    - ../ConfigAbilityAction/change_collider_surface
    - ../ConfigAbilityAction/set_surround_anchor
    - ../ConfigAbilityAction/set_combat_fixed_move_point
    - ../ConfigAbilityAction/set_avatar_hit_buckets
    - ../ConfigAbilityAction/reset_avatar_hit_buckets
    - ../ConfigAbilityAction/set_ai_skill_cd_multiplier
    - ../ConfigAbilityAction/register_ai_action_point
    - ../ConfigAbilityAction/release_ai_action_point
    - ../ConfigAbilityAction/set_neuron_enable
    - ../ConfigAbilityAction/set_neuron_mute
    - ../ConfigAbilityAction/broadcast_neuron_stimulate
    - ../ConfigAbilityAction/issue_command
    - ../ConfigAbilityAction/reset_ai_threat_broadcast_range
    - ../ConfigAbilityAction/set_ai_hit_feeling
    - ../ConfigAbilityAction/set_velocity_ignore_air_gy
    - ../ConfigAbilityAction/use_item
    - ../ConfigAbilityAction/repeated
    - ../ConfigAbilityAction/set_entity_scale
    - ../ConfigAbilityAction/call_lua_task
    - ../ConfigAbilityAction/dungeon_fog_effects
    - ../ConfigAbilityAction/do_tile_action
    - ../ConfigAbilityAction/do_watcher_system_action
    - ../ConfigAbilityAction/show_progress_bar_action
    - ../ConfigAbilityAction/change_tag
    - ../ConfigAbilityAction/use_skill_elite_set
    - ../ConfigAbilityAction/fixed_monster_rush_move
    - ../ConfigAbilityAction/fixed_avatar_rush_move
    - ../ConfigAbilityAction/attach_element_type_resistance
    - ../ConfigAbilityAction/add_global_value_to_target
    - ../ConfigAbilityAction/revive_elem_energy
    - ../ConfigAbilityAction/add_climate_meter
    - ../ConfigAbilityAction/reset_climate_meter
    - ../ConfigAbilityAction/fire_gain_crystal_seed_event
    - ../ConfigAbilityAction/enable_monster_move_on_water
    - ../ConfigAbilityAction/enable_avatar_move_on_water
    - ../ConfigAbilityAction/change_enviro_weather
    - ../ConfigAbilityAction/sync_entity_position_by_normalized_time
    - ../ConfigAbilityAction/equip_affix_start
    - ../ConfigAbilityAction/show_extra_ability
    - ../ConfigAbilityAction/set_extra_ability_enable
    - ../ConfigAbilityAction/set_extra_ability_state
    - ../ConfigAbilityAction/update_uid_value
    - ../ConfigAbilityAction/force_use_skill_success
    - ../ConfigAbilityAction/server_lua_call
    - ../ConfigAbilityAction/do_widget_system_action
    - ../ConfigAbilityAction/change_gadget_ui_interact_hint
    - ../ConfigAbilityAction/kill_play_entity
    - ../ConfigAbilityAction/dummy_action
    - ../ConfigAbilityAction/ban_entity_mark
    - ../ConfigAbilityAction/fire_ui_effect
    - ../ConfigAbilityAction/attach_ui_effect
    - ../ConfigAbilityAction/set_skill_anchor
    - ../ConfigAbilityAction/add_charge_value
    - ../ConfigAbilityAction/set_charge_ratio
    - ../ConfigAbilityAction/enable_light_core_component
    - ../ConfigAbilityAction/server_monster_log
    - ../ConfigAbilityAction/enable_position_synchronization
    - ../ConfigAbilityAction/revive_stamina
    - ../ConfigAbilityAction/add_charge_bar_value
    - ../ConfigAbilityAction/set_charge_bar_value
    - ../ConfigAbilityAction/set_ui_combat_bar_spark
    - ../ConfigAbilityAction/refresh_ui_combat_bar_layout
    - ../ConfigAbilityAction/enable_gadget_special_camera
    - ../ConfigAbilityAction/kill_server_gadget
    - ../ConfigAbilityAction/show_text_map
    - ../ConfigAbilityAction/fire_charge_bar_effect
    - ../ConfigAbilityAction/enable_weather_lock
    - ../ConfigAbilityAction/push_inter_action_by_config_path
    - ../ConfigAbilityAction/ignore_move_col_to_rock_col
    - ../ConfigAbilityAction/create_tile
    - ../ConfigAbilityAction/destroy_tile
    - ../ConfigAbilityAction/clear_tile
    - ../ConfigAbilityAction/change_shield_value
    - ../ConfigAbilityAction/fire_fishing_event
    - ../ConfigAbilityAction/send_evt_electric_core_move_enter_p1
    - ../ConfigAbilityAction/send_evt_electric_core_move_interrupt
    - ../ConfigAbilityAction/get_fight_property
    - ../ConfigAbilityAction/get_team_total_max_energy_to_overridemap
    - ../ConfigAbilityAction/predicated
    - ../ConfigAbilityAction/HealHp/revive_avatar
    - ../ConfigAbilityAction/HealHp/revive_dead_avatar
    - ../ConfigAbilityAction/CreateEntity/create_gadget
    - ../ConfigAbilityAction/CreateEntity/create_moving_platform
seq:
  - id: type_code
    type: aux_types::vlq_base128_le_u
  - id: data
    type:
      switch-on: type_code.value
      cases:
        0: config_ability_action
        1: base_utility_action
        2: apply_modifier
        3: apply_level_modifier
        4: attach_modifier
        5: remove_unique_modifier
        6: fire_effect
        7: fire_sub_emitter_effect
        8: fire_effect_for_storm
        9: fire_effect_to_target
        10: fire_hit_effect
        11: avatar_skill_start
        12: entity_do_skill
        13: avatar_enter_focus
        14: avatar_exit_focus
        15: avatar_enter_view_bias
        16: avatar_exit_view_bias
        17: avatar_exit_climb
        18: avatar_camera_param
        19: avatar_enter_camera_shot
        20: avatar_exit_camera_shot
        21: play_emo_sync
        22: control_emotion
        23: spawn_attach
        24: turn_direction
        25: turn_direction_to_pos
        26: set_camera_lock_time
        27: fire_monster_being_hit_after_image
        28: fire_avatar_being_hit_after_image
        29: attach_effect
        30: attach_light
        31: add_global_value
        32: set_global_value
        33: multiply_global_value
        34: copy_global_value
        35: set_global_value_list
        36: set_global_value_to_override_map
        37: set_random_override_map_value
        38: set_override_map_value
        39: set_crystal_shield_hp_to_override_map
        40: set_system_value_to_override_map
        41: set_global_value_by_target_distance
        42: clear_global_value
        43: sum_target_weight_to_self_global_value
        44: set_global_pos
        45: add_global_pos
        46: clear_global_pos
        47: set_global_dir
        48: push_pos
        49: clear_pos
        50: get_pos
        51: damage_by_attack_value
        52: heal_sp
        53: heal_hp
        54: lose_hp
        55: enable_rocket_jump
        56: force_trigger_jump
        57: enable_after_image
        58: act_time_slow
        59: trigger_ability
        60: remove_modifier
        61: set_ai_param
        62: act_camera_shake
        63: act_camera_radial_blur
        64: set_animator_bool
        65: set_animator_int
        66: set_animator_float
        67: set_animator_trigger
        68: reset_animator_trigger
        69: set_material_param_float_by_transform
        70: debug_log
        71: trigger_bullet
        72: trigger_attack_event
        73: trigger_attack_target_map_event
        74: enable_wet_electric_hit_box
        75: create_entity
        76: try_trigger_platform_start_move
        77: kill_gadget
        78: kill_self
        79: trigger_audio
        80: trigger_drop_equip_parts
        81: trigger_throw_equip_part
        82: trigger_create_gadget_to_equip_part
        83: trigger_aux_weapon_trans
        84: trigger_gadget_interactive
        85: trigger_set_visible
        86: trigger_set_cast_shadow
        87: trigger_set_pass_through
        88: trigger_set_renderers_enable
        89: trigger_hide_weapon
        90: trigger_taunt
        91: trigger_set_chest_lock
        92: clear_lock_target
        93: set_pose_bool
        94: set_pose_int
        95: set_pose_float
        96: trigger_face_animation
        97: enable_crash_damage
        98: set_crash_damage
        99: try_find_blink_point
        100: try_find_blink_point_by_born
        101: do_blink
        102: avatar_do_blink
        103: enable_hit_box_by_name
        104: enable_push_collider_name
        105: enable_scene_transform_by_name
        106: generate_elem_ball
        107: randomed
        108: hide_ui_bill_board
        109: send_effect_trigger
        110: change_follow_damp_time
        111: set_self_attack_target
        112: force_init_massive_entity
        113: enable_head_control
        114: enable_part_control
        115: start_dither
        116: summon
        117: attach_ability_state_resistance
        118: fire_ai_sound_event
        119: add_element_durability
        120: set_part_control_target
        121: drop_subfield
        122: enable_gadget_intee
        123: remove_velocity_force
        124: execute_group_trigger
        125: re_trigger_ai_skill_initial_cd
        126: set_ai_skill_cd_available_now
        127: set_ai_skill_gcd
        128: enable_ai_stealthy
        129: unlock_skill
        130: add_avatar_skill_info
        131: remove_avatar_skill_info
        132: set_can_die_immediately
        133: play_emoji_bubble
        134: attach_bullet_aim_point
        135: enable_bullet_collision_plugin_trigger
        136: guide_paimon_disappear_end
        137: set_paimon_look_at_camera
        138: paimon_action
        139: set_paimon_look_at_avatar
        140: set_paimon_temp_offset
        141: set_keep_in_air_velocity_force
        142: force_air_state_fly
        143: to_nearst_anchor_point
        144: push_dvalin_s01process
        145: set_dvalin_s01fly_state
        146: regist_to_stage_script
        147: sync_to_stage_script
        148: calc_dvalin_s04reborn_point
        149: trigger_player_die
        150: reset_enviro_eular
        151: set_emission_scaler
        152: enter_camera_lock
        153: show_ui_combat_bar
        154: show_screen_effect
        155: add_server_buff
        156: remove_server_buff
        157: modify_avatar_skill_cd
        158: modify_vehicle_skill_cd
        159: reset_ability_special
        160: enable_avatar_fly_state_trail
        161: show_reminder
        162: update_reaction_damage
        163: execute_gadget_lua
        164: set_weapon_bind_state
        165: set_weapon_attach_point_real_name
        166: set_avatar_can_shake_off
        167: enable_main_interface
        168: change_play_mode
        169: enable_camera_dof
        170: enable_hit_auto_redirect
        171: clear_endura
        172: rush_move
        173: reset_ai_attack_target
        174: reset_ai_resist_taunt_level
        175: change_collider_surface
        176: set_surround_anchor
        177: set_combat_fixed_move_point
        178: set_avatar_hit_buckets
        179: reset_avatar_hit_buckets
        180: set_ai_skill_cd_multiplier
        181: register_ai_action_point
        182: release_ai_action_point
        183: set_neuron_enable
        184: set_neuron_mute
        185: broadcast_neuron_stimulate
        186: issue_command
        187: reset_ai_threat_broadcast_range
        188: set_ai_hit_feeling
        189: set_velocity_ignore_air_gy
        190: use_item
        191: repeated
        192: set_entity_scale
        193: call_lua_task
        194: dungeon_fog_effects
        195: do_tile_action
        196: do_watcher_system_action
        197: show_progress_bar_action
        198: change_tag
        199: use_skill_elite_set
        200: fixed_monster_rush_move
        201: fixed_avatar_rush_move
        202: attach_element_type_resistance
        203: add_global_value_to_target
        204: revive_elem_energy
        205: add_climate_meter
        206: reset_climate_meter
        207: fire_gain_crystal_seed_event
        208: enable_monster_move_on_water
        209: enable_avatar_move_on_water
        210: change_enviro_weather
        211: sync_entity_position_by_normalized_time
        212: equip_affix_start
        213: show_extra_ability
        214: set_extra_ability_enable
        215: set_extra_ability_state
        216: update_uid_value
        217: force_use_skill_success
        218: server_lua_call
        219: do_widget_system_action
        220: change_gadget_ui_interact_hint
        221: kill_play_entity
        222: dummy_action
        223: ban_entity_mark
        224: fire_ui_effect
        225: attach_ui_effect
        226: set_skill_anchor
        227: add_charge_value
        228: set_charge_ratio
        229: enable_light_core_component
        230: server_monster_log
        231: enable_position_synchronization
        232: revive_stamina
        233: add_charge_bar_value
        234: set_charge_bar_value
        235: set_ui_combat_bar_spark
        236: refresh_ui_combat_bar_layout
        237: enable_gadget_special_camera
        238: kill_server_gadget
        239: show_text_map
        240: fire_charge_bar_effect
        241: enable_weather_lock
        242: push_inter_action_by_config_path
        243: ignore_move_col_to_rock_col
        244: create_tile
        245: destroy_tile
        246: clear_tile
        247: change_shield_value
        248: fire_fishing_event
        249: send_evt_electric_core_move_enter_p1
        250: send_evt_electric_core_move_interrupt
        251: get_fight_property
        252: get_team_total_max_energy_to_overridemap
        253: predicated
        254: revive_avatar
        255: revive_dead_avatar
        256: create_gadget
        257: create_moving_platform
        _: aux_types::error
