meta:
  id: disp__config_ability_predicate
  endian: le
  license: GPLv2
  imports:
    - ../../../../aux_types
    - ../config_ability_predicate
    - ../ConfigAbilityPredicate/relational_operation_predicate
    - ../ConfigAbilityPredicate/by_target_raycast_visiable
    - ../ConfigAbilityPredicate/by_hit_critical
    - ../ConfigAbilityPredicate/by_wet_hit_collider
    - ../ConfigAbilityPredicate/by_hit_box_name
    - ../ConfigAbilityPredicate/by_hit_box_type
    - ../ConfigAbilityPredicate/by_has_element
    - ../ConfigAbilityPredicate/by_has_ability_state
    - ../ConfigAbilityPredicate/by_not
    - ../ConfigAbilityPredicate/by_any
    - ../ConfigAbilityPredicate/by_has_attack_target
    - ../ConfigAbilityPredicate/by_target_is_ghost_to_enemy
    - ../ConfigAbilityPredicate/by_target_is_self
    - ../ConfigAbilityPredicate/by_target_element
    - ../ConfigAbilityPredicate/by_host_or_guest
    - ../ConfigAbilityPredicate/by_target_global_value
    - ../ConfigAbilityPredicate/by_scene_prop_state
    - ../ConfigAbilityPredicate/by_avatar_in_water_depth
    - ../ConfigAbilityPredicate/by_entity_types
    - ../ConfigAbilityPredicate/by_hit_impulse
    - ../ConfigAbilityPredicate/by_hit_element
    - ../ConfigAbilityPredicate/by_hit_strike_type
    - ../ConfigAbilityPredicate/by_is_move_on_water
    - ../ConfigAbilityPredicate/by_attack_tags
    - ../ConfigAbilityPredicate/by_scene_surface_type
    - ../ConfigAbilityPredicate/by_unlock_talent_param
    - ../ConfigAbilityPredicate/by_conductive
    - ../ConfigAbilityPredicate/by_skill_ready
    - ../ConfigAbilityPredicate/by_is_combat
    - ../ConfigAbilityPredicate/by_vehicle_is_combat
    - ../ConfigAbilityPredicate/by_stage_is_ready_temp
    - ../ConfigAbilityPredicate/by_item_number
    - ../ConfigAbilityPredicate/by_has_component_tag
    - ../ConfigAbilityPredicate/by_has_feature_tag
    - ../ConfigAbilityPredicate/by_avatar_element_type
    - ../ConfigAbilityPredicate/by_avatar_weapon_type
    - ../ConfigAbilityPredicate/by_avatar_body_type
    - ../ConfigAbilityPredicate/by_cur_team_has_feature_tag
    - ../ConfigAbilityPredicate/by_cur_team_has_element_type
    - ../ConfigAbilityPredicate/by_cur_team_element_type_sort
    - ../ConfigAbilityPredicate/by_cur_team_has_weapon_type
    - ../ConfigAbilityPredicate/by_cur_team_weapon_type_sort
    - ../ConfigAbilityPredicate/by_cur_team_has_body_type
    - ../ConfigAbilityPredicate/by_cur_team_body_type_sort
    - ../ConfigAbilityPredicate/by_big_team_has_feature_tag
    - ../ConfigAbilityPredicate/by_big_team_has_element_type
    - ../ConfigAbilityPredicate/by_big_team_element_type_sort
    - ../ConfigAbilityPredicate/by_big_team_has_weapon_type
    - ../ConfigAbilityPredicate/by_big_team_weapon_type_sort
    - ../ConfigAbilityPredicate/by_big_team_has_body_type
    - ../ConfigAbilityPredicate/by_big_team_body_type_sort
    - ../ConfigAbilityPredicate/by_attack_type
    - ../ConfigAbilityPredicate/by_entity_appear_vision_type
    - ../ConfigAbilityPredicate/by_element_trigger_entity_type
    - ../ConfigAbilityPredicate/by_element_reaction_source_type
    - ../ConfigAbilityPredicate/by_element_reaction_type
    - ../ConfigAbilityPredicate/by_target_config_id
    - ../ConfigAbilityPredicate/by_is_local_avatar
    - ../ConfigAbilityPredicate/by_target_gadget_state
    - ../ConfigAbilityPredicate/by_die_state_flag
    - ../ConfigAbilityPredicate/by_has_shield
    - ../ConfigAbilityPredicate/by_equip_affix_ready
    - ../ConfigAbilityPredicate/by_target_in_area
    - ../ConfigAbilityPredicate/by_is_target_camp
    - ../ConfigAbilityPredicate/by_has_child_gadget
    - ../ConfigAbilityPredicate/by_target_layout_area
    - ../ConfigAbilityPredicate/by_player_climate_type
    - ../ConfigAbilityPredicate/by_target_weather_name
    - ../ConfigAbilityPredicate/by_is_gadget_exist_around
    - ../ConfigAbilityPredicate/by_entity_is_alive
    - ../ConfigAbilityPredicate/by_monster_air_state
    - ../ConfigAbilityPredicate/by_game_time_is_locked
    - ../ConfigAbilityPredicate/by_target_is_caster
    - ../ConfigAbilityPredicate/by_hit_element_durability
    - ../ConfigAbilityPredicate/by_has_tag
    - ../ConfigAbilityPredicate/by_current_scene_types
    - ../ConfigAbilityPredicate/by_target_type
    - ../ConfigAbilityPredicate/by_current_scene_id
    - ../ConfigAbilityPredicate/by_target_charge_value
    - ../ConfigAbilityPredicate/by_has_modifier
    - ../ConfigAbilityPredicate/by_find_blink_point_success
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_target_hp_ratio
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_local_avatar_stamina
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_local_avatar_stamina_ratio
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_target_hp_value
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_hit_damage
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_hit_en_break
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_target_override_map_value
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_target_weight
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_animator_float
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_animator_int
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_animator_bool
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_target_position_to_self_position
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_target_forward_and_self_position
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_self_forward_and_target_position
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_energy_ratio
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_energy
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_summon_tag_value
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_attack_not_hit_scene
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_target_altitude
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_compare_with_target
    - ../ConfigAbilityPredicate/RelationalOperationPredicate/by_global_pos_to_ground
seq:
  - id: type_code
    type: aux_types::vlq_base128_le_u
  - id: data
    type:
      switch-on: type_code.value
      cases:
        0: config_ability_predicate
        1: relational_operation_predicate
        2: by_target_raycast_visiable
        3: by_hit_critical
        4: by_wet_hit_collider
        5: by_hit_box_name
        6: by_hit_box_type
        7: by_has_element
        8: by_has_ability_state
        9: by_not
        10: by_any
        11: by_has_attack_target
        12: by_target_is_ghost_to_enemy
        13: by_target_is_self
        14: by_target_element
        15: by_host_or_guest
        16: by_target_global_value
        17: by_scene_prop_state
        18: by_avatar_in_water_depth
        19: by_entity_types
        20: by_hit_impulse
        21: by_hit_element
        22: by_hit_strike_type
        23: by_is_move_on_water
        24: by_attack_tags
        25: by_scene_surface_type
        26: by_unlock_talent_param
        27: by_conductive
        28: by_skill_ready
        29: by_is_combat
        30: by_vehicle_is_combat
        31: by_stage_is_ready_temp
        32: by_item_number
        33: by_has_component_tag
        34: by_has_feature_tag
        35: by_avatar_element_type
        36: by_avatar_weapon_type
        37: by_avatar_body_type
        38: by_cur_team_has_feature_tag
        39: by_cur_team_has_element_type
        40: by_cur_team_element_type_sort
        41: by_cur_team_has_weapon_type
        42: by_cur_team_weapon_type_sort
        43: by_cur_team_has_body_type
        44: by_cur_team_body_type_sort
        45: by_big_team_has_feature_tag
        46: by_big_team_has_element_type
        47: by_big_team_element_type_sort
        48: by_big_team_has_weapon_type
        49: by_big_team_weapon_type_sort
        50: by_big_team_has_body_type
        51: by_big_team_body_type_sort
        52: by_attack_type
        53: by_entity_appear_vision_type
        54: by_element_trigger_entity_type
        55: by_element_reaction_source_type
        56: by_element_reaction_type
        57: by_target_config_id
        58: by_is_local_avatar
        59: by_target_gadget_state
        60: by_die_state_flag
        61: by_has_shield
        62: by_equip_affix_ready
        63: by_target_in_area
        64: by_is_target_camp
        65: by_has_child_gadget
        66: by_target_layout_area
        67: by_player_climate_type
        68: by_target_weather_name
        69: by_is_gadget_exist_around
        70: by_entity_is_alive
        71: by_monster_air_state
        72: by_game_time_is_locked
        73: by_target_is_caster
        74: by_hit_element_durability
        75: by_has_tag
        76: by_current_scene_types
        77: by_target_type
        78: by_current_scene_id
        79: by_target_charge_value
        80: by_has_modifier
        81: by_find_blink_point_success
        82: by_target_hp_ratio
        83: by_local_avatar_stamina
        84: by_local_avatar_stamina_ratio
        85: by_target_hp_value
        86: by_hit_damage
        87: by_hit_en_break
        88: by_target_override_map_value
        89: by_target_weight
        90: by_animator_float
        91: by_animator_int
        92: by_animator_bool
        93: by_target_position_to_self_position
        94: by_target_forward_and_self_position
        95: by_self_forward_and_target_position
        96: by_energy_ratio
        97: by_energy
        98: by_summon_tag_value
        99: by_attack_not_hit_scene
        100: by_target_altitude
        101: by_compare_with_target
        102: by_global_pos_to_ground
        _: aux_types::error
